name: Pre-commit linter

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repo
        uses: actions/checkout@v3

      - name: Install pre-commit and run hooks
        run: |
          pip install pre-commit
          pre-commit install --install-hooks
          pre-commit run --show-diff-on-failure --all-files
